### ISSUE TITLE
Will it be better to just use forEach -> push instead of map -> flatten?

### ISSUE THREAD

**Issue by edwincen** [jlaustill/unwind#1]
Thanks for your contributing unwind feature, just needed in my project.
However, would it be better to just use forEach and then directly push to result[]?
```javascript
const unwind = function (array, field) {
  let res = []
  array.forEach(item => {
    if (item[field]) {
      item[field].forEach(i => {
        let output = { ...item }
        output[field] = i
        res.push(output)
      })
    } else {
      res.push({ ...item })
    }
  })
  return res
}
```

**Comment by jlaustill** [comment]
Heya!  I'm not sure if that would perform better or not.  Did you try it and see if all the tests passed?  I think if this is actually getting used it would be worth it to flush out an entire set of tests and then try different approaches to find the one that had the best performance.  Let me know how it works for you :)
